# Generated by Django 5.1.3 on 2024-11-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidatos',
            fields=[
                ('cedula_candidatos', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula_empleados', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('puesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('cedula_pocisiones', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Contrataciones',
            fields=[
                ('cedula_contrataciones', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cedula_candidatos', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratos.candidatos')),
                ('cedula_pocisiones', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Contratos.posiciones')),
            ],
        ),
    ]
